name: CI

on:
  push:
    branches: 
      - master
env:
  SCHEME: "LiveNews"
  DEVICE: "iPhone 11"
  DERIVED_DATA_PATH: "DerivedData"
  
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Action Checkout V2
        uses: actions/checkout@v2
      
      - name: Install gpg
        run: brew install gnupg
      
      - name: Switch XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.2.app
      
      - name: Setup provisioning profile
        run: ./.github/secrets/decrypt_secrets.sh
        env:
          IOS_PROFILE_KEY: ${{ secrets.IOS_PROFILE_KEY }}
      
      - name: Build app
        run: |
          xcodebuild archive \
            -project LiveNews.xcodeproj \
            -scheme LiveNews \
            -sdk iphoneos \
            -archivePath 'build/LiveNews.xcarchive' 
            PROVISIONING_PROFILE="profile.mobileprovision.gpg" \
            CODE_SIGN_IDENTITY="iPhone Distribution: GE Consumer & Industrial (BQ7X69DNU7)"
            
      - name: Export app
        run: |
          xcodebuild -exportArchive \
            -archivePath 'build/LiveNews.xcarchive' \
            -exportPath "build/LiveNews.ipa" \
            -exportOptionsPlist 'LiveNews/exportOptionsPlist.plist' \
            -allowProvisioningUpdates
            
      - name: Deploy to App Center
        run: |
          npm install appcenter-cli@2.3.3
          npx appcenter distribute release --token "${{secrets.APP_CENTER_TOKEN}}"  --file "build/LiveNews.ipa" --release-notes "$(git log -1 --pretty=format:%s)" --debug
