name: CI

on:
  push:
    branches: 
      - master
env:
  SCHEME: "LiveNews"
  DEVICE: "iPhone 11"
  DERIVED_DATA_PATH: "DerivedData"
  
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Action
        uses: actions/checkout@master
      - name: Build
        run: |
          xcodebuild archive \
            -project LiveNews.xcodeproj \
            -scheme $SCHEME \
            -sdk iphoneos13.2 \
            -configuration Debug \
            -archivePath $PWD/build/appname.xcarchive \
            IPHONEOS_DEPLOYMENT_TARGET=9.0
            PROVISIONING_PROFILE="profile.mobileprovision.gpg" \
            CODE_SIGN_IDENTITY="iPhone Distribution: GE Consumer & Industrial (BQ7X69DNU7)"
      - name: Export app
        run: |
          cd ios && xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/appname.xcarchive \
            -exportOptionsPlist $PWD/ci.plist \
            -exportPath $PWD/build
