name: CI

on:
  push:
    branches: 
      - master
env:
  SCHEME: "LiveNews"
  DEVICE: "iPhone 11"
  DERIVED_DATA_PATH: "DerivedData"
  
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Action
        uses: actions/checkout@master
      - name: Build
        run: |
          set -o pipefail && xcodebuild build -scheme $SCHEME -destination "platform=iOS Simulator,name=$DEVICE" -derivedDataPath $DERIVED_DATA_PATH build-for-testing | xcpretty --color --simple
