name: CI

on:
  push:
    branches: 
      - master
env:
  SCHEME: "LiveNews"
  DEVICE: "iPhone 11"
  DERIVED_DATA_PATH: "DerivedData"
  
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Action
        uses: actions/checkout@master
      - name: Build
        run: |
          xcodebuild archive \
            -workspace LiveNews.xcodeproj \
            -scheme $SCHEME \
            -sdk iphoneos13.2 \
            -configuration Debug \
            -archivePath $PWD/build/appname.xcarchive \
            IPHONEOS_DEPLOYMENT_TARGET=9.0
